### ISSUE TITLE
Add denom-metadata support

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#123]
**Is your feature request related to a problem? Please describe.**
`emd q bank denom-metadata` returns

```
metadatas: []
pagination:
  next_key: null
  total: "0"
```

**Describe the solution you'd like**
The query return the list of support tokens with exponent=6 (similar to "tokens" section of https://api.e-money.com/v1/tokens.json).
