### ISSUE TITLE
Returned denom-metadata does not match genesis

### ISSUE THREAD

**Issue by mdyring** [e-money/em-ledger#139]
Returned denom-metadata is not as expected: 

```
% emd q bank denom-metadata                                                                                                                                                                                      metadatas:
- base: echf
  denom_units:
  - aliases: []
    denom: echf
    exponent: 6
  description: ""
  display: ""
- base: edkk
  denom_units:
  - aliases: []
    denom: edkk
    exponent: 6
  description: ""
  display: ""
- base: eeur
  denom_units:
  - aliases: []
    denom: eeur
    exponent: 6
  description: ""
  display: ""
- base: enok
  denom_units:
  - aliases: []
    denom: enok
    exponent: 6
  description: ""
  display: ""
- base: esek
  denom_units:
  - aliases: []
    denom: esek
    exponent: 6
  description: ""
  display: ""
- base: ungm
  denom_units:
  - aliases: []
    denom: ungm
    exponent: 0
  - aliases: []
    denom: ngm
    exponent: 6
  description: e-Money NGM staking token
  display: NGM
```

Above was ran against lilmermaid-16 where the [genesis.json](https://github.com/e-money/networks/blob/master/lilmermaid-16/genesis.json) contains more information.
